### PR TITLE
Fixed a few more grammar issues not completed in time for https://github.com/archcraft-os/archcraft-os.github.io/pull/1

### PR DESCRIPTION
**Pull request by NlGHT**
This is a sort of continuation from the last pull request as their were a few things that didn't make it in time.  Of course grammar and english will likely be an ongoing matter, but just a few things stood out.  Now it's more about phrasing.  On this there is still the conversation around https://github.com/archcraft-os/archcraft-os.github.io/pull/1#discussion_r458971640 which has not quite been verified yet, but I tried a new one so let me know what you think @tiosgz.

### CODE REVIEW

**Comment by ghost** [comment]
LGTM, except for that *There **is** no 32-bit or ARM editions.*

**Comment by NlGHT** [comment]
> LGTM, except for that _There **is** no 32-bit or ARM editions._

Fixed!

**Comment by adi1090x** [comment]
you sure that line 116 won't break the layout of the website?

**Comment by ghost** [comment]
> you sure that line 116 won't break the layout of the website?

It doesn’t. Only the [changes](https://github.com/archcraft-os/archcraft-os.github.io/pull/1/files#diff-eacf331f0ffc35d4b482f1d15a887d3bL141) from #1 seem to have made the WM block too small.

**Comment by NlGHT** [comment]
> you sure that line 116 won't break the layout of the website?

Yes it doesn't.  However it is of course able to be changed to something else if you don't like it!  I'm not even really a huge fan of it myself in a lot of ways, so open to suggestions.  But, I also think it's not the worst.

image

**Comment by adi1090x** [comment]
Alright, you guys have done some work on this website & I'm thankful for that. So i wanted to ask you guys... can you take a look at whole website & fix the errors, typos and other stuff. make English better on this site. I don't have time for that so I'm just hopping that you guys can do it.

**Comment by NlGHT** [comment]
Maybe if I happen to come by at some point in the future i'll commit something I see that's out.  But, truth be told, I personally really don't have time for constant checking either sadly. :cry: I mainly originally came through just to fix a few minor things because I really liked the project idea and felt bad and it unfair that grammar was holding it back.  Again though, if I do ever spot something in the future I will pick up on it and fix it up.  It's in a really nice spot right now I have to say though, nothing really out of place that will make someone turn away or something.  There are also others that I see have made PR's with grammar fixes, maybe they'll come through!

Been hoping to see a distro like this for a long time and glad it's happened! :smile: Good stuff!
Also huge thanks to @tiosgz for helping out.  Basically half the work was him and he fixed a ton of MY *fixes* too!

**Comment by ghost** [comment]
I’ll review the rest of pages (yes I’ve really only looked at the main page yet) tomorrow (hopefully). I’m watching this repo now so I think I’ll check any future changes (I can’t promise but I’ll try).

> Also huge thanks to @tiosgz for helping out. Basically half the work was him and he fixed a ton of MY fixes too!

Well I think it’s better to fix all in one PR (or two, if the first is merged early) instead of duplicating the work and having to resolve conflicts…

**Comment by adi1090x** [comment]
> Well I think it’s better to fix all in one PR

That would be really great. Please, whenever you get time, do it for this project.
Thank you @tiosgz & @NlGHT

**Pull request merged**
